spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: question-service-route
          uri: lb://question-service
          predicates:
            - Path=/question/**
        - id: quiz-service-route
          uri: lb://quiz-service
          predicates:
            - Path=/quiz/**
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://service-registry:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin-server:9411/api/v2/spans

logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
  level:
    root: INFO
    org.springframework: INFO
    org.springframework.cloud: DEBUG
    brave.Tracer: DEBUG
    com.uv: DEBUG
