global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'api-gateway'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['api-gateway:8080']

  - job_name: 'question-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['question-service:8081']

  - job_name: 'quiz-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['quiz-service:8082']

  - job_name: 'service-registry'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['service-registry:8761']
