spring.application.name=zipkin-server
server.port=9411
spring.main.web-application-type=none
spring.autoconfigure.exclude=org.springframework.boot.actuate.autoconfigure.metrics.export.prometheus.PrometheusMetricsExportAutoConfiguration
armeria.enableMetrics=true
armeria.ports[0].port=${server.port}
armeria.ports[0].protocols[0]=http
armeria.internal-services.include=health,metrics,actuator

# RabbitMQ Configuration for Zipkin Message Ingestion
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
spring.rabbitmq.connection-timeout=5000

# Zipkin Storage Configuration
zipkin.storage.type=mem

# Actuator configuration
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

# Logging Configuration
logging.level.root=INFO
logging.level.zipkin2=DEBUG
logging.level.org.springframework.amqp=DEBUG

